
  CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "INGRESA_SISTEMAS_ANEXOS"."VST_INSOLVENCIA_EXTRACT" ("RUT", "DV", "FECHA_PUBLICACION", "ROL", "TRIBUNAL", "NOMBRE_PUBLICACION", "TIPO_PROCEDIMIENTO", "GRUPO") AS 
  SELECT
    SUBSTR(A.RUT,0,INSTR(A.RUT,'-') - 1) AS RUT,
    SUBSTR(A.RUT,-1) AS DV,
    A.FECHAPUBLICACION AS FECHA_PUBLICACION,
    A.ROLCAUSA AS ROL, 
    A.TRIBUNAL AS TRIBUNAL,
    A.NOMBREPUBLICACION AS NOMBRE_PUBLICACION,
    A.TIPOPROCEDIMIENTO AS  TIPO_PROCEDIMIENTO,
    CASE 
        WHEN TRANSLATE(UPPER(A.TIPOPROCEDIMIENTO), 'ÁÉÍÓÚÑ', 'AEIOUN') LIKE '%LIQUIDACION%' THEN 'Liquidación'
        WHEN TRANSLATE(UPPER(A.TIPOPROCEDIMIENTO), 'ÁÉÍÓÚÑ', 'AEIOUN') LIKE '%RENEGOCIACIÓN%' THEN 'Renegociación' 
        ELSE 'Otro'
    END AS GRUPO
FROM INSOLVENCIA_SCRAPPER A
WHERE EXISTS(
    SELECT 1 
    FROM INGRESA_HISTORICO H 
    WHERE H.RUT = SUBSTR(A.RUT,0,INSTR(A.RUT,'-') - 1)
)

